// Code generated by scripts/generateMcpCatalog.mjs; DO NOT EDIT.
package mcpserver

type Scenario struct {
	ID            string `json:"id"`
	Title         string `json:"title"`
	Group         string `json:"group"`
	BackendStatus string `json:"backendStatus"`
}
type CatalogOutput struct {
	Scenarios []Scenario `json:"scenarios"`
}

var scenarioCatalog = []Scenario{
	{ID: "O01", Title: "工作台与待办", Group: "office", BackendStatus: "browser-only"},
	{ID: "O02", Title: "人员与组织", Group: "office", BackendStatus: "browser-only"},
	{ID: "O03", Title: "公告与通知", Group: "office", BackendStatus: "browser-only"},
	{ID: "O04", Title: "邮件与内部消息", Group: "office", BackendStatus: "browser-only"},
	{ID: "O05", Title: "日程与会议", Group: "office", BackendStatus: "browser-only"},
	{ID: "O06", Title: "文档与知识库", Group: "office", BackendStatus: "browser-only"},
	{ID: "O07", Title: "表格与数据处理", Group: "office", BackendStatus: "browser-only"},
	{ID: "O08", Title: "通用审批", Group: "office", BackendStatus: "browser-only"},
	{ID: "O09", Title: "差旅与费用", Group: "office", BackendStatus: "browser-only"},
	{ID: "O10", Title: "人事与考勤", Group: "office", BackendStatus: "browser-only"},
	{ID: "O11", Title: "采购与供应商", Group: "office", BackendStatus: "browser-only"},
	{ID: "O12", Title: "合同与用印", Group: "office", BackendStatus: "browser-only"},
	{ID: "O13", Title: "资产与行政", Group: "office", BackendStatus: "browser-only"},
	{ID: "O14", Title: "项目与任务协作", Group: "office", BackendStatus: "browser-only"},
	{ID: "O15", Title: "IT 服务与权限", Group: "office", BackendStatus: "browser-only"},
	{ID: "O16", Title: "统计报表与档案", Group: "office", BackendStatus: "browser-only"},
	{ID: "S01", Title: "客户资料审核与适当性匹配", Group: "securities", BackendStatus: "browser-only"},
	{ID: "S02", Title: "研报编制、审阅与发布", Group: "securities", BackendStatus: "browser-only"},
	{ID: "S03", Title: "投行立项与尽调协作", Group: "securities", BackendStatus: "browser-only"},
	{ID: "S04", Title: "风险预警调查与处置", Group: "securities", BackendStatus: "browser-only"},
	{ID: "S05", Title: "机构客户服务与路演协同", Group: "securities", BackendStatus: "browser-only"},
	{ID: "P01", Title: "两层发现与标准调用", Group: "protocol", BackendStatus: "browser-protocol-only"},
	{ID: "P02", Title: "Schema 与字段错误", Group: "protocol", BackendStatus: "browser-protocol-only"},
	{ID: "P03", Title: "只读动态校验", Group: "protocol", BackendStatus: "browser-protocol-only"},
	{ID: "P04", Title: "revision 与合同更新", Group: "protocol", BackendStatus: "browser-protocol-only"},
	{ID: "P05", Title: "生命周期与多实例", Group: "protocol", BackendStatus: "browser-protocol-only"},
	{ID: "P06", Title: "异步取消与迟到结果", Group: "protocol", BackendStatus: "browser-protocol-only"},
	{ID: "P07", Title: "重复请求与业务幂等", Group: "protocol", BackendStatus: "browser-protocol-only"},
	{ID: "P08", Title: "受控错误与异常归一", Group: "protocol", BackendStatus: "browser-protocol-only"},
	{ID: "P09", Title: "动态合同与最新状态", Group: "protocol", BackendStatus: "browser-protocol-only"},
	{ID: "P10", Title: "容量与隔离", Group: "protocol", BackendStatus: "browser-protocol-only"},
}
