// No dependencies or execution of application code. Generated inventory is not a
// registry: browser-only actions must never become callable through this script.
import { readFile, readdir, writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { spawnSync } from 'node:child_process';

const root = fileURLToPath(new URL('../', import.meta.url));
const check = process.argv.includes('--check');
async function files(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  return (await Promise.all(entries.map(e => e.isDirectory() ? files(path.join(dir, e.name)) : [path.join(dir, e.name)]))).flat();
}
const source = await readFile(path.join(root, 'frontend/src/common/scenarios/catalog.ts'), 'utf8');
const scenarios = [...source.matchAll(/\{ id: '([^']+)', title: '([^']+)', group: '([^']+)' \}/g)].map(([, id, title, group]) => ({ id, title, group, backendStatus: group === 'protocol' ? 'browser-protocol-only' : 'browser-only' }));
const actions = new Map();
for (const file of (await files(path.join(root, 'frontend/src/pc'))).filter(f => f.endsWith('.tsx')).sort()) {
  const text = await readFile(file, 'utf8');
  for (const [, action] of text.matchAll(/action:\s*'([^']+)'/g)) {
    if (action.startsWith('protocol.')) continue;
    const entry = actions.get(action) ?? { action, tool: action.replace(/[.-]/g, '_'), status: action === 'demo.analysis.query' ? 'implemented' : 'pending-domain-migration', sources: [] };
    entry.sources.push(path.relative(root, file)); actions.set(action, entry);
  }
}
const names = new Set();
for (const entry of actions.values()) { if (names.has(entry.tool)) throw new Error(`Tool name collision: ${entry.tool}`); names.add(entry.tool); }
const inventory = { generatedBy: 'scripts/generateMcpCatalog.mjs', note: 'Static Action inventory; not an executable registry. Dynamic browser Actions require separate review.', scenarios, actions: [...actions.values()].sort((a,b) => a.action.localeCompare(b.action)) };
const go = `// Code generated by scripts/generateMcpCatalog.mjs; DO NOT EDIT.\npackage mcpserver\n\ntype Scenario struct {\n\tID string \x60json:"id"\x60\n\tTitle string \x60json:"title"\x60\n\tGroup string \x60json:"group"\x60\n\tBackendStatus string \x60json:"backendStatus"\x60\n}\ntype CatalogOutput struct { Scenarios []Scenario \x60json:"scenarios"\x60 }\nvar scenarioCatalog = []Scenario{\n${scenarios.map(s => `\t{ID: ${JSON.stringify(s.id)}, Title: ${JSON.stringify(s.title)}, Group: ${JSON.stringify(s.group)}, BackendStatus: ${JSON.stringify(s.backendStatus)}},`).join('\n')}\n}\n`;
const formatted=spawnSync('gofmt',[],{input:go,encoding:'utf8'});
if(formatted.status!==0) throw new Error('gofmt failed: '+formatted.stderr);
for (const [relative, content] of [['contracts/mcp/action-mapping.json', JSON.stringify(inventory, null, 2)+'\n'], ['backend/internal/mcpserver/catalog_generated.go', formatted.stdout]]) {
  const target = path.join(root, relative);
  if (check) { if (await readFile(target, 'utf8') !== content) throw new Error(`Stale generated file: ${relative}`); }
  else { await mkdir(path.dirname(target), { recursive: true }); await writeFile(target, content); }
}
console.log(`${scenarios.length} scenarios, ${actions.size} unique business Actions: ${check ? 'verified' : 'generated'}`);
