// Local demo acceptance: no dependencies, no secret output, no reset operations.
import assert from 'node:assert/strict';
import { createHash, randomBytes } from 'node:crypto';
const base = process.env.AWCP_DEMO_URL ?? 'http://127.0.0.1:2181';
const address = new URL(base);
if (address.protocol!=='http:' || !['127.0.0.1','localhost','[::1]'].includes(address.hostname) || address.pathname!=='/' || address.search || address.hash || address.username || address.password) throw new Error('Smoke login is restricted to a loopback HTTP origin');
const endpoint = base+'/mcp';
const username = process.env.AWCP_MCP_USERNAME ?? 'demo';
const password = process.env.AWCP_MCP_PASSWORD ?? 'demo';
const nonce = html => html.match(/name="nonce" value="([^"]+)"/)?.[1];
const cookie = response => response.headers.get('set-cookie')?.split(';')[0];
const get = path => fetch(base+path,{redirect:'manual',signal:AbortSignal.timeout(10000)});
const post = (path,form,browserCookie) => fetch(base+path,{method:'POST',redirect:'manual',signal:AbortSignal.timeout(10000),headers:{'Content-Type':'application/x-www-form-urlencoded',Origin:base,...(browserCookie?{Cookie:browserCookie}:{})},body:new URLSearchParams(form)});
const page=await get('/api/v1/mcp/connect');assert.equal(page.status,200);
const login=await post('/api/v1/mcp/connect/start',{nonce:nonce(await page.text()),username,password},cookie(page));assert.equal(login.status,200);
const html=await login.text();const token=html.match(/spellcheck="false">([^<]+)<\/textarea>/)?.[1];assert.ok(token,'login token');
process.env.AWCP_MCP_PUBLIC_URL=endpoint;process.env.AWCP_MCP_ACCESS_TOKEN=token;
await import('./mcpSmoke.mjs');
const probe=token=>fetch(endpoint,{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:'{}',signal:AbortSignal.timeout(10000)});
assert.equal((await post('/oauth/revoke',{token,client_id:'wrong-client'})).status,200);
assert.notEqual((await probe(token)).status,401);
assert.equal((await post('/oauth/revoke',{token,client_id:'demo-portal'})).status,200);
assert.equal((await probe(token)).status,401);
const discovery=await get('/.well-known/oauth-authorization-server');const metadata=await discovery.json();assert.equal(metadata.issuer,base);
const registered=await fetch(metadata.registration_endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({client_name:'Local smoke test',redirect_uris:['http://127.0.0.1:8989/callback'],token_endpoint_auth_method:'none',grant_types:['authorization_code'],response_types:['code']}),signal:AbortSignal.timeout(10000)});assert.equal(registered.status,201);
const client=await registered.json();const verifier=randomBytes(32).toString('base64url');const challenge=createHash('sha256').update(verifier).digest('base64url');
const authURL=new URL(metadata.authorization_endpoint);authURL.search=new URLSearchParams({client_id:client.client_id,redirect_uri:client.redirect_uris[0],response_type:'code',state:'smoke-state',resource:endpoint,scope:'context:read reports:read',code_challenge:challenge,code_challenge_method:'S256'});
const authPage=await fetch(authURL,{redirect:'manual',signal:AbortSignal.timeout(10000)});assert.equal(authPage.status,200);
const consent=await post(authURL.pathname,{nonce:nonce(await authPage.text()),username,password},cookie(authPage));assert.equal(consent.status,303);
const callback=new URL(consent.headers.get('location'));assert.equal(callback.origin,'http://127.0.0.1:8989');assert.equal(callback.searchParams.get('iss'),base);assert.equal(callback.searchParams.get('state'),'smoke-state');
const grant={grant_type:'authorization_code',client_id:client.client_id,redirect_uri:client.redirect_uris[0],resource:endpoint,code:callback.searchParams.get('code'),code_verifier:verifier};
assert.equal((await post('/oauth/token',{...grant,resource:base+'/wrong-resource'})).status,400);
const exchanged=await post('/oauth/token',grant);assert.equal(exchanged.status,200);const tokens=await exchanged.json();assert.equal(tokens.token_type,'Bearer');
assert.notEqual((await probe(tokens.access_token)).status,401);
assert.equal((await post('/oauth/token',grant)).status,400);
assert.equal((await probe(tokens.access_token)).status,401);
console.log('PASS: real demo login, client-bound revocation, discovery, registration, consent, PKCE, audience binding, code replay rejection. No token printed or stored.');
